# Generated by Django 4.2.7 on 2024-01-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlename', models.CharField(max_length=100)),
                ('directorname', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=100)),
                ('heroinename', models.CharField(max_length=100)),
                ('titlename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movies')),
            ],
        ),
    ]
